name: NPM Publish

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - id: calculate
        name: Set env
        run: |
          export NIGHTLY_VERSION=$(echo "0.0.0-$(date +%m%d%Y-%H%M)-${GITHUB_SHA::9}")
          echo "::set-output name=nightly_version::${NIGHTLY_VERSION}"
    outputs:
      nightly_version: ${{ steps.calculate.outputs.nightly_version }}
        
  test:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Update package.json version to "${{ needs.version.outputs.nightly_version }}"
        if: github.event.release.prerelease == true
        run: echo "${{ needs.version.outputs.nightly_version }}-rc.0"
      - name: Update package.json version to "${{ needs.version.outputs.nightly_version }}"
        if: github.event.release.prerelease == false
        run: echo "${{ needs.version.outputs.nightly_version }}"
