name: NPM Publish Nightly

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'     

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - id: calculate
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          export NIGHTLY_VERSION=$(echo "0.0.0-$(date +%m%d%Y-%H%M)-${GITHUB_SHA::9}")
          echo "::set-output name=nightly_version::${NIGHTLY_VERSION}"
      - name: Test
        run: echo "${{ NIGHTLY_VERSION }}"
    outputs:
      nightly_version: ${{ steps.calculate.outputs.nightly_version }}
        
  test:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Update package.json version to "${{ needs.version.outputs.nightly_version }}"
        run: echo "${{ needs.version.outputs.nightly_version }}"
