name: NPM Publish Nightly

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  nightly_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "NIGHTLY_VERSION=$(echo `0.0.0-$(date +%m%d%Y-%H%M)-${GITHUB_SHA::9}`)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT
        
  test:
    runs-on: ubuntu-latest
    needs: nightly_version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Update package.json version to ${NIGHTLY_VERSION}
        run: echo $NIGHTLY_VERSION
